[package]
name = "space_game"
version = "0.1.0"
authors = ["Ricardo Delfin <me@rdelfin.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
ggez = { git = "https://github.com/rdelfin/ggez" }
thiserror = "1.0.15"
